<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Malzeme;
use App\Models\Fnote;

use SimpleSoftwareIO\QrCode\Facades\QrCode;
//use PDF; // If you created the alias

use ZipArchive;

class BROCHURE_PDF extends \TCPDF {

    public function Header() {

        $this->SetY(10);

        $this->SetFillColor(216, 226, 220);
        $this->Rect(0, 0, $this->getPageWidth(), PDF_MARGIN_TOP, 'F');

        $this->SetFillColor(45, 145, 220);

        $this->ImageSVG($file='/images/mtlogo.svg', $x=10, $y=10, $w='', $h='10', $link=url('/'), $align='', $palign='', $border=0, $fitonpage=false);
        $this->ImageSVG($file='/images/pdm_logo2.svg', $x=186, $y=6, $w='16', $h='', $link=url('/'), $align='', $palign='', $border=0, $fitonpage=false);

        $this->SetXY(35,17);
    }

    public function Footer() {

        $this->ImageSVG($file="/images/baykus_orange.svg", $x=8, $y=285, $w='6', $h='6', $link='https://kapkara.one', $align='', $palign='', $border=0, $fitonpage=false);

        $this->SetXY(14,290);
        $this->SetFont('helvetica', '', 6);

        $this->Cell(30, 0, 'kapkara.one', 0, false, 'L', 0, '', 0, false, 'M', 'M');

        $this->SetXY(170,290);
        $this->Cell(30, 0, 'masttech.net', 0, false, 'R', 0, '', 0, false, 'M', 'M');
        $this->SetXY(170,287);

        $this->Cell(30, 0, 'PDM Product Data Management', 0, false, 'R', 0, '', 0, false, 'M', 'M');
    }
}



class PDFProductBrochure extends Controller
{

    public $pdf_fname;
    public $tree_items;
    public $parents = [];





    public function generatePdf()
    {




        $pdf = new BROCHURE_PDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'utf-8', false);

        $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT,PDF_MARGIN_BOTTOM);

        $pdf->SetCreator('Automatically generated by PDM');
        $pdf->SetAuthor('kapkara.one');
        $pdf->SetTitle('Product Brochure');

        $pdf->AddPage();

        // $pdf->SetY(50);
        // $pdf->SetFont('dejavusans', '', 16);

        // $pdf->Cell(0, 0, 'ÜRÜN VERİSİ / BILL OF MATERIALS', 0, false, 'C', 0, '', 0, false, 'M', 'M');

        // $pdf->SetXY(PDF_MARGIN_LEFT,60);

        // $qr = QrCode::generate($url);

        // $pdf->ImageSVG($file="@$qr", $x=10, $y=60, $w='20', $h='20', $link="$url", $align='', $palign='', $border=0, $fitonpage=false);

        // $pdf->SetXY(32,60);

        // $pdf->SetFont('dejavusans', 'B', 24);
        // $pdf->Cell(50, 10, $item->part_number.'-'.$item->version, 0, $ln=0, 'L', 0, '', 0, false, 'T', 'T');

        // $pdf->SetXY(32,70);
        // $pdf->SetFont('dejavusans', '', 12);
        // $pdf->SetTextColor(131, 133, 140);

        // $pdf->MultiCell(142, 8, $item->description, 0, 'L', 0, 0, '', '', true);
        // $pdf->SetTextColor(0,0,0);
        // $pdf->SetFont('dejavusans', '', 8);

        // $pdf->SetTextColor(35, 100, 170);

        // $pdf->SetXY(175,60);
        // $pdf->SetFillColor(230, 230, 230);
        // $pdf->SetTextColor(0,0,0);

        // $pdf->Cell(25, 5, 'ECN-'.$item->c_notice_id, 0, $ln=0, 'C', 1, '', 0, false, 'T', 'C');
        // $pdf->SetXY(175,66);
        // $pdf->Cell(25, 5, $item->weight.' kg', 0, $ln=0, 'C', 1, '', 0, false, 'T', 'C');

        // $pdf->Ln();
        // $pdf->SetY(90);


        $fname = 'BOM_R';

        $this->pdf_fname = '/tmp/'.$fname.'.pdf';

            $pdf->Output($fname, 'I'); // 'I' means inline, you can change it to 'D' to force download


    }











}


